-- CREATE DATABASE dbContacts;

-- USE dbContacts;

CREATE TABLE tblSMS (
    sms_ID INT AUTO_INCREMENT PRIMARY KEY,
    studno VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    cpno VARCHAR(20) NOT NULL
);
